### PR TITLE
Handle lock matching better and clean up

### LINKED ISSUE #20: Replace should check for exact line from beginning to end
We have had in few occasions the mutex queue file de-queue-ing 2 lines instead of 1 because the file contained:
```
8068190887-1709052162-60
8068190887-1709052162-600
```
And while dequeing `8068190887-1709052162-60` it removed `8068190887-1709052162-600` as well. Then the other lock infinitely waited for `8068190887-1709052162-600`.

Additionally if the queue file is empty, `wait_for_lock` should exit

### LINKED ISSUE #21: Replace awk commands for more specific commands
awk is a powerful multi tool command but it can be quite hard to read. I would suggest the following:

* read the top of the file with `head`
```
cat $__queue_file | awk NF | head -n 1
becomes
head -n 1 $__queue_file
```

* check for the ticket id via `grep -qx` (match whole line)
```
$(awk "/$__ticket_id/" $__queue_file | wc -l) == "0"
becomes
grep -qx "$__ticket_id" "$__queue_file"
```

* Remove the top line of the queue via `sed`:
```
awk "!/$__ticket_id/" $__queue_file | awk NF > ${__queue_file}.new
mv ${__queue_file}.new $__queue_file

becomes
sed -i '1d' $__queue_file
```

### PR DESCRIPTION
**Pull request by Fran-Rg**
Resolves #20 
Resolves #21
Closes #23

### CODE REVIEW

**Comment by Fran-Rg** [comment]
I'm currently testing further the PR as there were some issues.

Looks like the actions are locked and require approval to run: https://github.com/ben-z/gh-action-mutex/actions/runs/8095240799

**Comment by ben-z** [comment]
Approved, seems to be the same issue

**Comment by ben-z** [comment]
Strange, runs fine in https://github.com/ben-z/gh-action-mutex/pull/23

Perhaps it's a permission issue with forks (https://github.com/ben-z/gh-action-mutex/issues/15).

**Comment by ben-z** [comment]
LGTM! Thanks for the contribution. Merging.

**Comment by ben-z** [comment]
Released in https://github.com/ben-z/gh-action-mutex/releases/tag/v1.0.0-alpha.9

**Pull request merged**
